# Generated by Django 3.2.4 on 2021-06-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_auto_20210624_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.TextField(default='Good Patient'),
            preserve_default=False,
        ),
    ]
